'use strict';
const $ = (s, root=document) => root.querySelector(s);
const main = $('#main');
const modal = $('#modal');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = n => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const state = {channel:'All',query:'',compare:new Set(),serviceStep:1,service:{model:'',need:'Scheduled service',branch:'Help me choose',date:'',time:'Morning'},financeMode:'emi'};
const modelById = id => SEHGAL.models.find(m => m.id === id);
const external = (url,label) => `<a class="text-link" href="${url}" target="_blank" rel="noopener noreferrer">${label} <span aria-hidden="true">↗</span></a>`;
const link = (href,label,style='') => `<a class="button ${style}" href="#/${href}">${label}<span aria-hidden="true">↗</span></a>`;
const request = (label,context,style='') => `<button class="button ${style}" data-request="${esc(context)}">${label}<span aria-hidden="true">↗</span></button>`;
function page(title,subtitle,eyebrow='SEHGAL AUTORIDERS') { return `<div class="page-heading"><div class="container"><div class="breadcrumb"><a href="#/">Home</a> / ${esc(title)}</div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${subtitle}</p></div></div>`; }
function credit(id) {const p=SEHGAL.photos[id];return p.oem?`<figcaption class="photo-credit">Official Maruti Suzuki image · <a href="${p.source}" target="_blank" rel="noopener noreferrer">View model details ↗</a></figcaption>`:`<figcaption class="photo-credit">${p.note}. <a href="${p.source}" target="_blank" rel="noopener noreferrer">${p.creator}</a> · ${p.license}</figcaption>`;}
function photo(id,cls='') {const p=SEHGAL.photos[id];return `<figure class="reference-photo ${cls} ${p.oem?'oem-photo':''}"><img src="${cls==='detail-photo'&&p.detailSrc?p.detailSrc:p.src}" alt="${p.alt}" loading="${cls==='hero-photo'?'eager':'lazy'}" decoding="async">${cls==='card-photo'&&p.oem?'':credit(id)}</figure>`;}
function card(m) {return `<article class="vehicle-card ${SEHGAL.photos[m.id]?'':'type-card'}">${SEHGAL.photos[m.id]?photo(m.id,'card-photo'):`<div class="type-card-top"><span>${esc(m.channel)}</span><span>${m.id==='e-vitara'?'ELECTRIC':'EXPLORE THE RANGE'}</span></div>`}<div class="vehicle-body"><p class="eyebrow">MARUTI SUZUKI ${m.channel.toUpperCase()}</p><div class="vehicle-title"><h3>${m.name}</h3><span aria-hidden="true">↗</span></div><p>${m.copy}</p><div class="vehicle-card-bottom"><a class="text-link" href="#/cars/${m.id}">Explore ${m.name}</a><button class="compare-toggle" data-compare="${m.id}" aria-pressed="${state.compare.has(m.id)}">${state.compare.has(m.id)?'✓ Added':'+ Compare'}</button></div></div></article>`;}
function home() {return `${campaignHome()}${channelEntrances()}<div class="journey-rail"><a href="#/cars"><span class="journey-number">01</span><span><b>Find your fit</b><small>Arena & NEXA</small></span><span class="rail-arrow">↗</span></a><a href="#/finance"><span class="journey-number">02</span><span><b>Make a plan</b><small>Budget & finance</small></span><span class="rail-arrow">↗</span></a><a href="#/service"><span class="journey-number">03</span><span><b>Care for your car</b><small>Service & ownership</small></span><span class="rail-arrow">↗</span></a><a href="#/commercial"><span class="journey-number">04</span><span><b>Move your business</b><small>Commercial Manjri</small></span><span class="rail-arrow">↗</span></a></div>${essentials()}
  <section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">EXPLORE OUR CARS</p><h2>Explore Arena<br>and NEXA.</h2></div><a class="text-link" href="#/cars">Explore the full range <span>↗</span></a></div><div class="vehicle-grid">${SEHGAL.models.slice(0,3).map(card).join('')}</div><p class="section-note">Explore the current Maruti Suzuki range. Our team can confirm variants, colours and local availability.</p></div></section>
  <section class="section wash"><div class="container"><div class="split-feature finance-feature"><div class="feature-copy"><p class="eyebrow">CAR FINANCE</p><h2>Plan your<br>car budget.</h2><p>Enter your monthly budget, down payment and loan term to estimate the amount you could finance.</p>${link('finance','Explore my budget','teal')}</div><div class="budget-art"><span class="eyebrow">YOUR PLAN STARTS HERE</span><p class="budget-amount">₹15,000<span>/ month</span></p><div><span>Your down payment</span><span>+ Your loan term</span><span>+ An assumed rate</span></div><small>Illustrative planning example · not a finance offer</small></div></div></div></section>
  <section class="section"><div class="container"><div class="duo"><article class="story-panel dark"><p class="eyebrow">THE ELECTRIC CENTRE</p><h2>Explore<br>electric driving.</h2><p>Learn about e VITARA, home charging and the costs of electric ownership.</p><div class="actions">${link('electric','Explore electric','light')}</div></article><article class="story-panel"><p class="eyebrow">SEHGAL COMMERCIAL · MANJRI</p><h2>Commercial vehicles<br>for your business.</h2><p>Speak to our Manjri team about your load, routes, vehicle requirements and finance options.</p><div class="actions">${link('commercial','Let’s talk business')}</div></article></div></div></section>
  <section class="section wash"><div class="container"><div class="service-banner"><div><p class="eyebrow">WE’RE HERE FOR THE LONG RUN</p><h2>Book your next<br>service visit.</h2><p>Arrange scheduled maintenance, repairs or bodyshop support for your Maruti Suzuki.</p>${link('service','Plan a service')}</div><div class="service-items"><a href="#/service">Scheduled service ↗</a><a href="#/service">Repairs & bodyshop ↗</a><a href="#/owners">Owner’s manuals ↗</a><a href="#/help">Get support ↗</a></div></div></div></section>${homeGallery()}`;}
function cars() {return page('Explore Maruti Suzuki cars','Browse Arena and NEXA models, compare your shortlist and speak to our sales team.','BUY A CAR')+`<section class="page-content"><div class="container"><div class="filter-bar"><div class="chips" aria-label="Filter by channel">${['All','Arena','NEXA'].map(c=>`<button class="chip ${state.channel===c?'active':''}" data-channel="${c}" aria-pressed="${state.channel===c}">${c==='All'?'All cars':c}</button>`).join('')}</div><label class="field"><span class="visually-hidden">Search model names</span><input id="model-search" type="search" placeholder="Search a model" value="${esc(state.query)}"></label></div><div class="booking-actions"><button class="button teal" data-book="test-drive">Book a test drive ↗</button><button class="button outline" data-book="sales">Book a sales appointment ↗</button></div><div id="vehicle-results">${carResults()}</div><p class="section-note">Official Maruti Suzuki model images. Colours, variants, prices and local availability are subject to confirmation.</p><div class="callout"><h3>Prefer to start with a budget?</h3><p class="muted">See how your monthly amount and down payment fit together.</p>${link('finance','Plan my budget')}</div></div></section>`;}
function carResults(){const list=SEHGAL.models.filter(m=>(state.channel==='All'||state.channel===m.channel)&&m.name.toLowerCase().includes(state.query.toLowerCase()));return `<p class="meta" role="status">${list.length} models in this view</p><div class="vehicle-grid">${list.map(card).join('')}</div>${list.length?'':'<div class="empty"><h3>No matching models</h3><p>Try a different name or choose All cars.</p></div>'}`;}
function modelPage(id){const m=modelById(id);if(!m)return notFound();return `<section class="page-content"><div class="container"><div class="breadcrumb"><a href="#/cars">All cars</a> / ${m.name}</div><div class="model-layout">${SEHGAL.photos[id]?photo(id,'detail-photo'):`<div class="model-editorial"><p class="eyebrow">MARUTI SUZUKI ${m.channel.toUpperCase()}</p><p class="editorial-model">${m.name}</p><span>LET’S FIND YOUR NEXT CHAPTER.</span></div>`}<div class="model-intro"><p class="eyebrow">MARUTI SUZUKI ${m.channel.toUpperCase()}</p><h1>${m.name}</h1><p class="muted">${m.copy}</p><div class="spec-grid"><div class="spec-cell"><small>Catalogue</small><b>${m.channel}</b></div><div class="spec-cell"><small>Local availability</small><b>Check with Sehgal</b></div><div class="spec-cell"><small>Price</small><b>Request a quote</b></div></div><div class="actions">${request('Book a test drive',m.name,'teal')}<button class="button outline" data-book="sales" data-model="${esc(m.name)}">Book a sales appointment ↗</button><button class="button outline" data-compare="${id}">${state.compare.has(id)?'✓ In shortlist':'+ Add to compare'}</button></div><p class="fine-print">Your preferred test drive is subject to vehicle and appointment availability. This shared preview demonstrates the booking steps without sending a request.</p></div></div><div class="section"><div class="model-tabs" role="tablist" aria-label="Vehicle information">${['Overview & specs','Price & finance','Ownership'].map((t,i)=>`<button role="tab" id="tab-${i}" aria-controls="model-panel" aria-selected="${i===0}" tabindex="${i===0?'0':'-1'}" data-model-tab="${i}" data-model-id="${id}" class="${i===0?'active':''}">${t}</button>`).join('')}</div><div id="model-panel" class="model-tab-content" role="tabpanel" aria-labelledby="tab-0">${modelTab(m,0)}</div></div></div></section>`;}
function modelTab(m,index){return [ `${modelSpecSummary(m.id)}<h3>Start with the official details.</h3><p class="muted">Explore current specifications and brochures at ${m.channel}. Your Sehgal advisor can then help with local options, pricing and availability.</p>${external(SEHGAL.photos[m.id].source,`View official ${m.name} details`)+(m.channel==='NEXA'?' '+external('https://www.nexaexperience.com/e-brochure','NEXA brochures'):'')}`, `<h3>Build a plan around your budget.</h3><p class="muted">An on-road quote should separate the vehicle price, applicable registration costs, insurance and selected extras. Ask our team for an itemised quote and the applicable finance terms.</p>${link('finance','Compare lenders & EMI','small')} ${link('insurance','Insurance','outline small')}`, `<h3>Support beyond your next car.</h3><p class="muted">Keep service, official manuals and help within easy reach.</p><div class="actions">${link('service','Plan service','small')}${link('owners','Owners’ centre','outline small')}</div>` ][index];}
function finance(){return page('Plan your car finance','Work out an indicative monthly payment, or start with what you want to spend each month. No account needed.','FINANCE & BUDGET')+`<section class="page-content"><div class="container"><div class="chips finance-chips"><button class="chip ${state.financeMode==='emi'?'active':''}" data-finance-mode="emi">Calculate monthly payment</button><button class="chip ${state.financeMode==='budget'?'active':''}" data-finance-mode="budget">Start with my monthly budget</button></div><div class="finance-layout"><form id="finance-form" class="panel"><h3>${state.financeMode==='emi'?'Plan a possible loan':'What could I plan for?'}</h3><p class="muted">All numbers below are editable assumptions.</p><div class="form-grid"><label class="field">${state.financeMode==='emi'?'Illustrative vehicle budget (₹)':'Monthly payment budget (₹)'}<input name="amount" type="number" min="${state.financeMode==='emi'?1:0}" max="100000000" step="1" value="${state.financeMode==='emi'?1000000:15000}" required></label><label class="field">Down payment (₹)<input name="down" type="number" min="0" max="100000000" step="1" value="200000" required></label><label class="field">Assumed annual interest (%)<input name="rate" type="number" min="0" max="50" step="0.1" value="9" required><small>Illustration only; not a lender rate.</small></label><label class="field">Loan term (months)<select name="months"><option value="36">36 months · 3 years</option><option value="48">48 months · 4 years</option><option value="60" selected>60 months · 5 years</option><option value="72">72 months · 6 years</option><option value="84">84 months · 7 years</option></select></label></div><p class="notice">Estimates exclude lender fees and any costs outside your entered budget. A lender must confirm eligibility, rate and the final repayment schedule.</p></form><aside class="finance-result" id="finance-result" aria-live="polite"></aside></div>${financeExtras()}<div class="callout"><h3>The right next step is a clear quote.</h3><p class="muted">Compare itemised costs, understand the loan terms and choose the extras that suit you. Finance remains subject to lender eligibility and approval.</p>${request('Enquire about finance','Finance')}</div></div></section>`;}
function updateFinance(){const form=$('#finance-form');if(!form)return;const result=$('#finance-result');if(!form.checkValidity()){result.innerHTML='<h3>Check your numbers</h3><p>Enter valid amounts, a rate from 0–50% and a loan term.</p>';return;}const f=new FormData(form),a=Number(f.get('amount')),d=Number(f.get('down')),r=Number(f.get('rate')),n=Number(f.get('months'));if(state.financeMode==='emi'&&d>a){result.innerHTML='<h3>Check the down payment</h3><p>It cannot exceed your entered vehicle budget.</p>';return;}const loan=state.financeMode==='emi'?a-d:budgetEstimate(a,r,n,d).principal;const out=loanEstimate(loan,r,n);result.innerHTML=`<p class="eyebrow">ILLUSTRATIVE ESTIMATE</p><p>${state.financeMode==='emi'?'Monthly payment':'Potential vehicle budget'}</p><div class="big-number">${money(state.financeMode==='emi'?out.emi:loan+d)}</div><p class="meta">${state.financeMode==='emi'?'per month':'including your entered down payment'}</p><dl><div><dt>Loan principal</dt><dd>${money(loan)}</dd></div><div><dt>Total interest</dt><dd>${money(out.interest)}</dd></div><div><dt>Loan repayments</dt><dd>${money(out.total)}</dd></div></dl><p class="meta">${n} months · ${r}% assumed annual rate<br>Not an offer, sanction or affordability assessment.</p>`;}
function service(){return serviceContent();}
function electric(){return page('Explore electric ownership','Explore the car. Understand charging. Put everyday running costs into perspective. Start your EV journey with a clear view.','THE SEHGAL ELECTRIC CENTRE')+`<section class="page-content"><div class="container">${nexaIntro()}${campaignPicture('e-vitara')}<div class="tiles section"><article class="tile"><p class="eyebrow">01 · AT HOME</p><h3>Your charging setup</h3><p class="muted">Discuss your parking space, electricity supply and installation requirements with our team.</p></article><article class="tile"><p class="eyebrow">02 · ON THE ROAD</p><h3>Your everyday routes</h3><p class="muted">Think about your commute, longer trips and access to compatible public charging.</p></article><article class="tile"><p class="eyebrow">03 · OVER TIME</p><h3>Your ownership plan</h3><p class="muted">Use the current OEM documents for battery warranty, maintenance and vehicle-specific guidance.</p></article></div><div class="panel"><div class="section-heading"><div><p class="eyebrow">EXPLORE THE NUMBERS</p><h2>What might energy cost?</h2></div><p class="muted">An editable illustration of electricity cost only. Charging losses, installation, finance and other ownership costs are excluded.</p></div><form id="ev-form" class="form-grid"><label class="field">Distance each month (km)<input name="km" type="number" min="0" max="50000" step="1" value="1000" required></label><label class="field">Assumed use (kWh / 100 km)<input name="use" type="number" min="1" max="100" step="0.1" value="15" required></label><label class="field">Electricity price (₹ / kWh)<input name="price" type="number" min="0" max="200" step="0.1" value="10" required></label><div class="energy-result" id="ev-result" aria-live="polite"></div></form><p class="fine-print">Values are user-editable assumptions, not e VITARA consumption specifications or a published electricity tariff.</p></div><div class="callout"><h3>Make it relevant to your life.</h3><p class="muted">Local display vehicles, test drives, charging support and availability need branch confirmation.</p><button class="button" data-book="sales" data-model="e VITARA">Speak to our EV team ↗</button></div></div></section>`;}
function commercial(){return commercialContent();}
function locations(){return locationsContent();}
function owners(){return page('Service and owner resources','Find official information, plan your service and reach the right support. Older models belong here too.','OWNERS’ CENTRE')+`<section class="page-content"><div class="container"><div class="tiles"><article class="tile"><p class="eyebrow">01 · OFFICIAL RESOURCES</p><h3>Owner’s manuals</h3><p class="muted">Choose the official resource for your channel and match your model, year and variant.</p>${external('https://www.marutisuzuki.com/arena/car-manuals','Arena owner’s manuals')}${external('https://www.nexaexperience.com/car-manual','NEXA manuals')}</article><article class="tile"><p class="eyebrow">02 · LOOKING AFTER YOUR CAR</p><h3>Service & repairs</h3><p class="muted">Request a service visit for current or older Maruti Suzuki models.</p>${link('service','Plan service','small')}</article><article class="tile"><p class="eyebrow">03 · PARTS, INSURANCE & SAFETY</p><h3>Everything else for your car</h3><p class="muted">Genuine spares, insurance renewal and claims, and crash-test ratings.</p><div class="actions">${link('spares','Spares','outline small')}${link('insurance','Insurance','outline small')}${link('safety','Safety','outline small')}</div></article><article class="tile"><p class="eyebrow">04 · YOUR SEHGAL</p><h3>One place for your car</h3><p class="muted">My Sehgal is planned for saved vehicles, confirmed appointments and approved documents.</p><span class="location-tag">Planned · account services not connected</span></article></div><div class="section"><h2>A little clarity goes a long way.</h2><div class="faq-list"><details><summary>Can I find help for an older model?</summary><p>Yes. Our service form includes older models. Use the official manual for your model and year, and ask your workshop about the work your vehicle needs.</p></details><details><summary>Does a service request confirm an appointment?</summary><p>Your request records a preferred date and time. The dealership must confirm availability before it becomes an appointment. This shared preview does not send or save requests.</p></details><details><summary>Where will I find my invoices and history?</summary><p>Those are planned for My Sehgal after secure identity and dealership-system integration. They are not available in this design preview.</p></details></div></div></div></section>`;}
function help(){return helpContent();}
function about(){return aboutContent();}
function notFound(){return page('Let’s get you back on the road.','This page is not part of the design preview.')+`<div class="container page-content">${link('','Back to home')}</div>`;}
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function formatDate(date){return date?date.split('-').reverse().join('-'):'Not selected';}
function toast(message){const t=$('#toast');t.textContent=message;t.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',3200);}
function openDialog(html){$('#modal-content').innerHTML=html;if(!modal.open)modal.showModal();}
function closeDialog(){modal.close();$('#modal-content').innerHTML='';}
function requestDialog(context){connectedRequest(context);}
function compareDialog(){const list=[...state.compare].map(modelById);openDialog(`<p class="eyebrow">YOUR SHORTLIST</p><h2 id="modal-title">Side by side.</h2>${list.length?`<p class="modal-subtitle">Official specifications, with the source linked in each column.</p><a class="button small teal" href="#/compare/${list.map(m=>m.id).join(',')}">Open the full comparison ↗</a>${specTable(list.map(m=>m.id))}`:'<p>Add up to three cars from the catalogue.</p>'}`);}
function syncCompare(){let tray=$('#compare-tray');if(!state.compare.size){tray?.remove();return;}if(!tray){tray=document.createElement('div');tray.id='compare-tray';tray.className='compare-tray';document.body.append(tray);}tray.innerHTML=`<span><b>${state.compare.size} ${state.compare.size===1?'car':'cars'} shortlisted</b><br><span class="meta">${[...state.compare].map(id=>modelById(id).name).join(' · ')}</span></span><button class="button teal small" data-action="compare">Compare ↗</button><button class="tray-clear" data-action="clear-compare" aria-label="Clear shortlist">×</button>`;document.querySelectorAll('[data-compare]').forEach(b=>{const selected=state.compare.has(b.dataset.compare);b.setAttribute('aria-pressed',String(selected));b.textContent=selected?'✓ Added to shortlist':'+ Compare';});}
function searchDialog(){openDialog(`<h2 id="modal-title">What can we help you find?</h2><label class="field"><span class="visually-hidden">Search cars, service and more</span><input id="site-search" type="search" placeholder="Try “Swift”, “service” or “finance”" autofocus></label><div class="search-results" id="site-results"></div>`);searchResults('');}
function searchResults(query){const pages=[['Explore cars','cars'],['Book a service','service'],['Finance & monthly budget','finance'],['Electric centre','electric'],['Commercial Manjri','commercial'],['Owner’s manuals','owners'],['Locations','locations'],['Help & escalations','help'],['Hero motorcycles & scooters','two-wheelers'],['Photo gallery','gallery'],['Driving school','driving-school'],['Compare cars','compare'],['Insurance & No Claim Bonus','insurance'],['Spares & accessories','spares'],['Genuine parts price list','spares'],['Safety & crash-test ratings','safety'],['Service schedule & warranty','service'],['Compare lenders & EMI','finance'],['CSR · Corporate Social Responsibility','csr'],...SEHGAL.models.map(m=>[m.name,`cars/${m.id}`])];const list=pages.filter(([name])=>name.toLowerCase().includes(query.toLowerCase())).slice(0,8);$('#site-results').innerHTML=list.length?list.map(([n,p])=>`<a href="#/${p}">${n}<span>↗</span></a>`).join(''):'<p>No matches. Try a model name or service.</p>';}
function render(){if(location.hash==='#main'){main.focus();return;}const route=location.hash.replace(/^#\/?/,'').split('/');const key=route[0]||'home';const renders={home,cars,electric,commercial,service,finance,locations,owners,help,about,gallery,'driving-school':drivingSchool,'two-wheelers':heroContent,admin:adminContent,...EXTRA_ROUTES};main.innerHTML=key==='cars'&&route[1]?modelPage(route[1]):(renders[key]||notFound)();main.tabIndex=-1;document.title=`${key==='home'?'Your digital dealership':key==='csr'?'CSR':key.charAt(0).toUpperCase()+key.slice(1)} · Sehgal Autoriders · Design preview`;document.querySelectorAll('nav a').forEach(a=>{const active=a.hash===`#/${key}`||(key==='owners'&&a.hash==='#/service');a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('#navigation').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');$('.menu-toggle').setAttribute('aria-label','Open navigation');if(modal.open)closeDialog();syncCompare();updateFinance();updateEV();AFTER_RENDER.forEach(f=>f());window.scrollTo(0,0);}
function updateEV(){const f=$('#ev-form');if(!f)return;const target=$('#ev-result');if(!f.checkValidity()){target.textContent='Enter valid positive assumptions.';return;}const d=new FormData(f),cost=Number(d.get('use'))/100*Number(d.get('price'));target.innerHTML=`<span class="meta">Illustrative electricity cost</span><strong>${money(cost*Number(d.get('km')))} <small>/ month</small></strong><span>${money(cost).replace(/\d[\d,]*/,cost.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2}))} per km · energy only</span>`;}
document.addEventListener('click',event=>{const target=event.target.closest('button,a');if(!target)return;if(target.matches('.menu-toggle')){const open=$('#navigation').classList.toggle('open');target.setAttribute('aria-expanded',String(open));target.setAttribute('aria-label',open?'Close navigation':'Open navigation');}if(target.matches('.modal-close'))closeDialog();if(target.dataset.catalogue){state.channel=target.dataset.catalogue;state.query='';if(location.hash==='#/cars')render();}if(target.dataset.request)requestDialog(target.dataset.request);if(target.dataset.channel){state.channel=target.dataset.channel;render();}if(target.dataset.financeMode){state.financeMode=target.dataset.financeMode;render();}if(target.dataset.compare){const id=target.dataset.compare;if(state.compare.has(id))state.compare.delete(id);else if(state.compare.size<3)state.compare.add(id);else toast('Your shortlist can hold up to three cars.');syncCompare();}if(target.hasAttribute('data-service-back')){state.serviceStep=Math.max(1,state.serviceStep-1);render();}if(target.dataset.modelTab){const index=Number(target.dataset.modelTab),m=modelById(target.dataset.modelId);document.querySelectorAll('[data-model-tab]').forEach(b=>{const active=b===target;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});$('#model-panel').innerHTML=modelTab(m,index);$('#model-panel').setAttribute('aria-labelledby',target.id);}switch(target.dataset.action){case 'search':searchDialog();break;case 'compare':compareDialog();break;case 'clear-compare':state.compare.clear();syncCompare();break;case 'service-finish':openDialog('<p class="eyebrow">PREVIEW FINISHED</p><h2 id="modal-title">Your preference is ready to discuss.</h2><p>This rehearsal is complete. No booking has been created, no request has been sent and no appointment is confirmed.</p><a class="button" href="#/">Back to home ↗</a>');state.serviceStep=1;state.service={model:'',need:'Scheduled service',branch:'Help me choose',date:'',time:'Morning'};break;}if(target.tagName==='A'&&target.hash===location.hash&&modal.open)closeDialog();});
document.addEventListener('input',event=>{if(event.target.id==='model-search'){state.query=event.target.value;$('#vehicle-results').innerHTML=carResults();}if(event.target.id==='site-search')searchResults(event.target.value);if(event.target.closest('#finance-form'))updateFinance();if(event.target.closest('#ev-form'))updateEV();});
document.addEventListener('change',event=>{if(event.target.closest('#finance-form'))updateFinance();});
document.addEventListener('submit',event=>{if(event.target.id==='service-form'){event.preventDefault();Object.assign(state.service,Object.fromEntries(new FormData(event.target)));state.serviceStep=Math.min(3,state.serviceStep+1);render();}else if(event.target.id==='request-form'){event.preventDefault();openDialog('<p class="eyebrow">DESIGN REHEARSAL COMPLETE</p><h2 id="modal-title">A clear next step.</h2><p>In the live journey, you would review contact preferences and consent before sending your request. An acknowledgement would follow only after the dealership receives it.</p><p class="notice">Nothing was sent or booked. No customer information was collected.</p><button class="button" data-action="close">Back to exploring →</button>');}else if(['finance-form','ev-form'].includes(event.target.id))event.preventDefault();});
document.addEventListener('click',event=>{if(event.target.closest('[data-action="close"]'))closeDialog();});
document.addEventListener('keydown',event=>{if(event.target.matches('[data-model-tab]')&&['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const tabs=[...document.querySelectorAll('[data-model-tab]')],i=tabs.indexOf(event.target),next=event.key==='Home'?0:event.key==='End'?tabs.length-1:(i+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].focus();tabs[next].click();}});
modal.addEventListener('cancel',()=>{$('#modal-content').innerHTML='';});
window.addEventListener('hashchange',render);
render();
bootstrapOperations();
