'use strict';
let galleryCategory='All';
const suppliedAsset=id=>SUPPLIED_ASSETS.find(a=>a.id===id);
function suppliedFigure(id,extraClass=''){
  const a=suppliedAsset(id);
  return `<figure class="supplied-figure ${extraClass}"><button class="image-open" data-image="${a.id}" aria-label="View ${esc(a.title)}"><img src="${a.src}" alt="${esc(a.title)}" loading="lazy" decoding="async"></button><figcaption>${esc(a.title)}</figcaption></figure>`;
}
function galleryCard(a){return `<article class="gallery-card" data-gallery-category="${esc(a.category)}">${suppliedFigure(a.id)}<span class="gallery-category">${esc(a.category)}</span></article>`;}
function galleryResults(){const items=SUPPLIED_ASSETS.filter(a=>galleryCategory==='All'||a.category===galleryCategory);return `<p class="meta" role="status">${items.length} ${items.length===1?'image':'images'}</p><div class="gallery-grid">${items.map(galleryCard).join('')}</div>`;}
function gallery(){return page('Life at Sehgal','Customer deliveries, company milestones, community celebrations and campaign highlights.','OUR PEOPLE. OUR JOURNEYS.')+`<section class="page-content"><div class="container"><div class="archive-note">Campaign archive: offers, dates, contact details and vehicle specifications shown inside older artwork may have changed. Ask our team for current information.</div><div class="chips gallery-filters" aria-label="Filter images">${['All',...new Set(SUPPLIED_ASSETS.map(a=>a.category))].map(c=>`<button class="chip ${galleryCategory===c?'active':''}" data-gallery-filter="${esc(c)}" aria-pressed="${galleryCategory===c}">${esc(c)}</button>`).join('')}</div><div id="gallery-results">${galleryResults()}</div></div></section>`;}
function homeGallery(){return `<section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">LIFE AT SEHGAL</p><h2>Celebrating every<br>new beginning.</h2></div><a class="text-link" href="#/gallery">View our gallery ↗</a></div><div class="delivery-strip">${['delivery-01','delivery-02','delivery-03'].map(id=>suppliedFigure(id)).join('')}</div></div></section>`;}
function drivingSchool(){return page('Learn to drive with confidence.','Explore driving lessons with Sehgal and Maruti Suzuki Driving School. Speak to the team about courses, lesson availability and enrolment.','DRIVING SCHOOL')+`<section class="page-content"><div class="container"><div class="model-layout">${suppliedFigure('driving-school','campaign-feature')}<div><h2>Start with the right training.</h2><p class="muted">Tell us whether you are learning for the first time or returning to driving. We will help you find the next step.</p>${request('Enquire about lessons','Driving school')}<p class="fine-print">The supplied campaign is shown as an archive. Its offer, fees and contact details require confirmation.</p></div></div></div></section>`;}
function twoWheelers(){return page('Sehgal two-wheelers','Explore the two-wheeler side of Sehgal through our supplied campaign and anniversary archive.','MORE FROM SEHGAL')+`<section class="page-content"><div class="container"><div class="duo">${suppliedFigure('hero-pleasure-campaign','campaign-feature')}${suppliedFigure('anniversary-27-invitation','campaign-feature')}</div><div class="callout"><h3>Speak to the two-wheeler team.</h3><p class="muted">Check the current range, prices and branch availability before planning your visit.</p>${request('Make an enquiry','Two-wheelers')}</div></div></section>`;}
function openImage(id){const a=suppliedAsset(id);if(!a)return;modal.classList.add('image-dialog');openDialog(`<h2 id="modal-title">${esc(a.title)}</h2><img class="lightbox-image" src="${a.src}" alt="${esc(a.title)}"><p class="fine-print">${a.category==='Brand'?'Original logo supplied for enhancement.':'Supplied artwork, preserved as received. Historical offers, figures and contact details are not current confirmations.'}</p>`);}
document.addEventListener('click',event=>{const imageButton=event.target.closest('[data-image]');if(imageButton)openImage(imageButton.dataset.image);const filter=event.target.closest('[data-gallery-filter]');if(filter){galleryCategory=filter.dataset.galleryFilter;$('#gallery-results').innerHTML=galleryResults();document.querySelectorAll('[data-gallery-filter]').forEach(button=>{const active=button.dataset.galleryFilter===galleryCategory;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});}});
document.addEventListener('close',event=>{if(event.target.id==='modal')event.target.classList.remove('image-dialog');},true);
